# Generated by Django 3.1.4 on 2021-08-01 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='binanceuser',
            name='id',
        ),
        migrations.AlterField(
            model_name='binanceuser',
            name='telegram_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.telegramuser'),
        ),
    ]
