# Generated by Django 3.1.4 on 2021-08-02 11:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210801_1058'),
        ('signals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_price', models.FloatField(blank=True, null=True)),
                ('max_price', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='futuresignal',
            old_name='buy_position',
            new_name='buy_side',
        ),
        migrations.RemoveField(
            model_name='futuresignal',
            name='entry_price',
        ),
        migrations.AddField(
            model_name='futuresignal',
            name='long_position',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='futuresignal',
            name='order_type',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.CreateModel(
            name='SpotSignal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(blank=True, null=True)),
                ('symbol_name', models.CharField(blank=True, max_length=32, null=True)),
                ('stop_loss', models.FloatField(blank=True, null=True)),
                ('take_profit', models.FloatField(blank=True, null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('buy_side', models.BooleanField(default=True)),
                ('order_type', models.CharField(blank=True, max_length=32, null=True)),
                ('order_status', models.CharField(blank=True, max_length=32, null=True)),
                ('isin_next_level', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_prices', models.ManyToManyField(blank=True, related_name='spot_signals', to='signals.EntryPrice')),
                ('telegram_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.telegramuser')),
            ],
        ),
        migrations.CreateModel(
            name='SpotControler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_orders', models.ManyToManyField(related_name='first_orders', to='signals.SpotSignal')),
                ('second_orders', models.ManyToManyField(related_name='second_orders', to='signals.SpotSignal')),
            ],
        ),
        migrations.AddField(
            model_name='futuresignal',
            name='entry_prices',
            field=models.ManyToManyField(blank=True, related_name='future_signals', to='signals.EntryPrice'),
        ),
    ]
