# Generated by Django 3.1.4 on 2021-08-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0002_auto_20210802_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='TakeProfit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='futuresignal',
            name='buy_side',
        ),
        migrations.RemoveField(
            model_name='futuresignal',
            name='long_position',
        ),
        migrations.RemoveField(
            model_name='futuresignal',
            name='take_profit',
        ),
        migrations.RemoveField(
            model_name='spotsignal',
            name='buy_side',
        ),
        migrations.AddField(
            model_name='futuresignal',
            name='order_status',
            field=models.CharField(blank=True, choices=[('NEW', 'NEW'), ('PARTIALLY_FILLED', 'PARTIALLY_FILLED'), ('FILLED', 'FILLED'), ('CANCELED', 'CANCELED'), ('PENDING_CANCEL', 'PENDING_CANCEL'), ('REJECTED', 'REJECTED'), ('EXPIRED', 'EXPIRED')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='futuresignal',
            name='position',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='futuresignal',
            name='side',
            field=models.CharField(blank=True, choices=[('BUY', 'BUY'), ('SELL', 'SELL')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='spotsignal',
            name='side',
            field=models.CharField(blank=True, choices=[('BUY', 'BUY'), ('SELL', 'SELL')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='spotsignal',
            name='order_status',
            field=models.CharField(blank=True, choices=[('NEW', 'NEW'), ('PARTIALLY_FILLED', 'PARTIALLY_FILLED'), ('FILLED', 'FILLED'), ('CANCELED', 'CANCELED'), ('PENDING_CANCEL', 'PENDING_CANCEL'), ('REJECTED', 'REJECTED'), ('EXPIRED', 'EXPIRED')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='futuresignal',
            name='take_profits',
            field=models.ManyToManyField(blank=True, related_name='future_signals', to='signals.TakeProfit'),
        ),
    ]
