# Generated by Django 3.1.4 on 2021-08-02 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0003_auto_20210802_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotsignal',
            name='take_profit',
        ),
        migrations.AddField(
            model_name='futuresignal',
            name='isin_next_level',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='spotsignal',
            name='take_profits',
            field=models.ManyToManyField(blank=True, related_name='spot_signals', to='signals.TakeProfit'),
        ),
    ]
