# Generated by Django 3.1.7 on 2021-08-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0005_takeprofit_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotcontroler',
            name='cancel_orders',
            field=models.ManyToManyField(related_name='cancel_orders', to='signals.SpotSignal'),
        ),
    ]
