# Generated by Django 3.1.7 on 2021-08-03 14:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0007_spotsignal_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotsignal',
            name='isin_next_level',
        ),
        migrations.RemoveField(
            model_name='spotsignal',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='spotsignal',
            name='order_status',
        ),
        migrations.RemoveField(
            model_name='spotsignal',
            name='order_type',
        ),
        migrations.RemoveField(
            model_name='spotsignal',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='spotsignal',
            name='side',
        ),
        migrations.AddField(
            model_name='spotcontroler',
            name='spot_signal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='signals.spotsignal'),
        ),
        migrations.CreateModel(
            name='SpotOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(blank=True, null=True)),
                ('symbol_name', models.CharField(blank=True, max_length=32, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('stop_loss', models.FloatField(blank=True, null=True)),
                ('take_profit', models.FloatField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=32, null=True)),
                ('status', models.CharField(blank=True, choices=[('NEW', 'NEW'), ('PARTIALLY_FILLED', 'PARTIALLY_FILLED'), ('FILLED', 'FILLED'), ('CANCELED', 'CANCELED'), ('PENDING_CANCEL', 'PENDING_CANCEL'), ('REJECTED', 'REJECTED'), ('EXPIRED', 'EXPIRED')], max_length=32, null=True)),
                ('side', models.CharField(blank=True, choices=[('BUY', 'BUY'), ('SELL', 'SELL')], max_length=32, null=True)),
                ('isin_next_level', models.BooleanField(default=False)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('spot_signal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='signals.spotsignal')),
            ],
        ),
        migrations.AlterField(
            model_name='spotcontroler',
            name='cancel_orders',
            field=models.ManyToManyField(related_name='cancel_orders', to='signals.SpotOrder'),
        ),
        migrations.AlterField(
            model_name='spotcontroler',
            name='first_orders',
            field=models.ManyToManyField(related_name='first_orders', to='signals.SpotOrder'),
        ),
        migrations.AlterField(
            model_name='spotcontroler',
            name='second_orders',
            field=models.ManyToManyField(related_name='second_orders', to='signals.SpotOrder'),
        ),
    ]
