# Generated by Django 3.1.7 on 2021-08-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0008_auto_20210803_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotorder',
            name='volume',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
