# Generated by Django 3.1.7 on 2021-08-03 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0009_spotorder_volume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotcontroler',
            name='cancel_orders',
        ),
    ]
